#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     getCmake
#
# Description
#     Get Cmake unpack it.
#
#------------------------------------------------------------------------------
cmakePACKAGE="cmake-2.8.3"

#------------------------------------------------------------------------------
# run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [cmake-VERSION]

* build combinations of cmake
    $cmakePACKAGE

USAGE
    exit 1
}

getFile() {
  packageDir=$1
  tarFile=$2
  url=$3

  if [ ! -d ${packageDir} ]
  then
      downloadFile $tarFile $url

      if [ -e download/$tarFile ]
      then
          echo "unpack download/$tarFile"
          tar -xf download/$tarFile
      else
          echo "no download/$tarFile to unpack"
      fi
  fi
}

# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    cmake-[2-9]*)
        cmakePACKAGE="${1%%/}"
        shift
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done

cmakeFile=$cmakePACKAGE.tar.gz
version=${cmakePACKAGE:6:3}

cmakeUrl="http://www.cmake.org/files/v${version}/$cmakeFile"

getFile ${cmakePACKAGE} ${cmakeFile} ${cmakeUrl}

# ----------------------------------------------------------------- end-of-file
