#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeBinutils
#
# Description
#     Build script for Binutils
#
#------------------------------------------------------------------------------
binutilsPACKAGE=binutils-2.20.1
gccPACKAGE=gcc-4.5.1

#------------------------------------------------------------------------------
# run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [binutils-VERSION] [gcc-VERSION]

* build combinations of binutils and currently built gcc
      $binutilsPACKAGE
      $gccPACKAGE

USAGE
    exit 1
}


# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    binutils-[2-9]*)
        binutilsPACKAGE="${1%%/}"
        shift
        ;;
    gcc-[4-9]*)
        gccPACKAGE="${1%%/}"
        shift
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done


# set 32 or 64 bit ABI
case "$WM_ARCH_OPTION" in
32 | 64)
    ABI=$WM_ARCH_OPTION
    ;;
*)
    usage "Please set WM_ARCH_OPTION to either 32 or 64'$*'"
    ;;
esac


#------------------------------------------------------------------------------
# build/install without compiler name
buildBASE=$WM_THIRD_PARTY_DIR/build/$WM_ARCH$WM_COMPILER_ARCH
installBASE=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH

BINUTILS_ARCH_PATH=$installBASE/$gccPACKAGE

#
# Build Binutils
#
echo "---------------"
if [ ! -d $BINUTILS_ARCH_PATH ]
then
    echo "$gccPACKAGE isn't built yet."
else
    echo "Starting build: $binutilsPACKAGE"
    echo
(
    sourceDIR=$WM_THIRD_PARTY_DIR/$binutilsPACKAGE
    buildDIR=$buildBASE/$binutilsPACKAGE

    cd $sourceDIR || exit 1
    make distclean 2>/dev/null

    rm -rf $buildDIR
    mkdir -p $buildDIR
    cd $buildDIR

    set -x
    $sourceDIR/configure ABI=$ABI \
        --prefix=$BINUTILS_ARCH_PATH \
        --enable-cxx \
    && make -j $WM_NCOMPPROCS \
    && make install \
    && echo "Built: $binutilsPACKAGE"
) || {
    echo "Error building: $binutilsPACKAGE"
    exit 1
}
fi

# ----------------------------------------------------------------- end-of-file
